files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/strings.xml
  - source: /app/src/main/res/values/sonora_strings.xml
    translation: /app/src/main/res/values-%android_code%/sonora_strings.xml
